CREATE DATABASE DB_CRUD

GO

USE DB_CRUD

CREATE TABLE [dbo].[TB_CATEGORIAS](
	[codigo_ca] [int] IDENTITY(1,1) NOT NULL,
	[descripcion_ca] [varchar](100) NULL,
	[activo] [bit] NULL,
 CONSTRAINT [PK_TB_CATEGORIAS] PRIMARY KEY CLUSTERED 
(
	[codigo_ca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TB_MEDIDAS](
	[codigo_me] [int] IDENTITY(1,1) NOT NULL,
	[descripcion_me] [nchar](20) NULL,
	[activo] [bit] NULL,
 CONSTRAINT [PK_TB_MEDIDAS] PRIMARY KEY CLUSTERED 
(
	[codigo_me] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TB_PRODUCTOS](
	[codigo_pr] [int] IDENTITY(1,1) NOT NULL,
	[descripcion_pr] [varchar](80) NULL,
	[marca_pr] [varchar](30) NULL,
	[codigo_me] [int] NULL,
	[codigo_ca] [int] NULL,
	[stock_actual] [decimal](18, 0) NULL,
	[fecha_cre] [datetime] NULL,
	[activo] [bit] NULL,
 CONSTRAINT [PK_TB_PRODUCTOS] PRIMARY KEY CLUSTERED 
(
	[codigo_pr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_PRODUCTOS]  WITH CHECK ADD  CONSTRAINT [FK_TB_PRODUCTOS_TB_CATEGORIAS] FOREIGN KEY([codigo_ca])
REFERENCES [dbo].[TB_CATEGORIAS] ([codigo_ca])
GO

ALTER TABLE [dbo].[TB_PRODUCTOS] CHECK CONSTRAINT [FK_TB_PRODUCTOS_TB_CATEGORIAS]
GO

ALTER TABLE [dbo].[TB_PRODUCTOS]  WITH CHECK ADD  CONSTRAINT [FK_TB_PRODUCTOS_TB_MEDIDAS] FOREIGN KEY([codigo_ca])
REFERENCES [dbo].[TB_MEDIDAS] ([codigo_me])
GO

ALTER TABLE [dbo].[TB_PRODUCTOS] CHECK CONSTRAINT [FK_TB_PRODUCTOS_TB_MEDIDAS]
GO
